# kitty-colors.conf
foreground            #f0e0ca
background            #191206
selection_background  #7d2c19
selection_foreground  #ffdad2
url_color             #ffb4a2
cursor                #ffb4a2
cursor_text_color     #5e1605

# Standard colors
color0  #191206
color1  #ffb4ab
color2  #ffb4a2
color3  #edc06c
color4  #ffb4a2
color5  #7d2c19
color6  #723425
color7  #f0e0ca
