# kitty-colors.conf
foreground            #f6decd
background            #1c1108
selection_background  #7d293d
selection_foreground  #ffd9de
url_color             #ffb2bd
cursor                #ffb2bd
cursor_text_color     #5f1127

# Standard colors
color0  #1c1108
color1  #ffb4ab
color2  #ffb2bd
color3  #ffb77c
color4  #ffb2bd
color5  #7d293d
color6  #72333f
color7  #f6decd
