# kitty-colors.conf
foreground            #dae6d9
background            #0c160e
selection_background  #4f4800
selection_foreground  #f4e569
url_color             #d7c950
cursor                #d7c950
cursor_text_color     #363100

# Standard colors
color0  #0c160e
color1  #ffb4ab
color2  #d7c950
color3  #98d5a4
color4  #d4c872
color5  #4f4800
color6  #4f4800
color7  #dae6d9
